server:
  port: 8082
  tomcat:
    uri-encoding: utf-8
spring:
  datasource: #msyql数据源
    url: jdbc:mysql://rm-2vc3309uy41ja7k8ngo.mysql.cn-chengdu.rds.aliyuncs.com:3306/cyblog?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=true&allowMultiQueries=true
    username: cinz
    password: zc@19990320
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
    dbcp2:
      max-idle: 10
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5

  jdbc:
    template:
      query-timeout: 50 #查询 x秒 未查询到，则判定为超时

  jackson: #date日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: cn.cinz.admin.model
